import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavBar from '@/components/NavBar'
import Resume from '@/components/Resume'
import { useState, useEffect } from 'react';
import { windowSize } from '@/utils/types';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [showLinks, setShowLinks] = useState<boolean>(false);
  const [windowSize, setWindowSize] = useState<windowSize>({
    width: window.innerWidth,
    height: window.innerHeight,
  })

  const trackScreenSizeChange = () => {
    setWindowSize({
      width: window.innerWidth,
      height: window.innerHeight
    })
  }

  useEffect(() => {
    window.addEventListener("resize", trackScreenSizeChange)

    return () => window.removeEventListener("resize", trackScreenSizeChange)
  }, [])

  return (
    <>
      <Head>
        <title>Pascal Kasonga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar showLinks={showLinks} setShowLinks={setShowLinks} />
      <div className="body-content">
        <Resume showLinks={showLinks} screenWidth={windowSize.width} />
      </div>
    </>
  )
}
